@startuml

namespace Inheritance{

QObject <|-- UiEditorHandle
UiEditorHandle <|-- UiObjectEditorHandle
UiObjectEditorHandle  <|-- UiWidgetObjectEditorHandle
UiObjectEditorHandle  <|-- Ui3dObjectEditorHandle
UiWidgetObjectEditorHandle <|-- UiFormLayoutObjectEditor
UiFormLayoutObjectEditor <|-- UiDefaultObjectEditor
UiFieldEditorHandle <|-- "Tons of field editors"
UiEditorHandle <|-- UiTreeItemEditor
UiEditorHandle <|-- UiTreeEditorHandle
UiEditorHandle <|-- UiToolBarEditor
UiEditorHandle <|-- UiTableRowEditor
UiEditorHandle <|-- UiFieldEditorHandle 

UiTreeEditorHandle  <|-- UiTreeViewEditor
}

Namespace TreeView{

QWidget <|-- UiTreeView

UiTreeView --* UiTreeViewEditor

UiTreeViewEditor --* 		UiTreeViewWidget 
UiTreeViewEditor --* 		UiTreeViewQModel 

UiTreeItemEditor -->  UiTreeViewEditor
UiTreeViewQModel --* "root"  UiTreeOrdering

UiTreeOrdering --> 	UiItem 
UiTreeOrdering --*  			UiTreeItemEditor

QTreeView <|-- UiTreeViewWidget

}

namespace Properties{

QWidget <|-- UiPropertyView

UiPropertyView --* UiDefaultObjectEditor
UiDefaultObjectEditor ---* "N" UiFieldEditorHandle

Field --> "N" UiFieldEditorHandle

UiFieldEditorHandle --> "1" Field 
UiDefaultObjectEditor  "N" <--> "1" edited_Object

edited_Object --* "N" Field

UiFieldEditorHandle --* QWidget_UsedByEditor
}

namespace 3DEditors{

SomeViewer --* UiSelection3dEditorVisualizer

UiSelection3dEditorVisualizer --* Ui3dObjectEditorHandle : "Creates on SelectionChanged()"

Ui3dObjectEditorHandle --> SomeViewer
Ui3dObjectEditorHandle --> 3DVisualizationStuff
Ui3dObjectEditorHandle -->edited_Object

}



@enduml