name: Build with Unit Tests

on: [push, pull_request]
jobs:
  caffa-x64:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run vcpkg
        uses: lukka/run-vcpkg@v6
        with:
          # Just install vcpkg for now, do not install any ports in this step yet.
          setupOnly: true
          # Location of the vcpkg as submodule of the repository.
          vcpkgDirectory: '${{ github.workspace }}/ThirdParty/vcpkg'
          vcpkgTriplet: ${{ matrix.triplet }}
      - name: Build Caffa with Unit Tests
        uses: lukka/run-cmake@v1
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          cmakeAppendedArgs: '-DCAFFA_GRPC_INTERFACE=ON -DVCPKG_AUTO_INSTALL=ON'
          buildDirectory: ${{ github.workspace }}/cmakebuild
          buildWithCMakeArgs: '--config Release'
      - name: Run Unit Tests Linux/MacOS
        if: "!contains( matrix.os, 'windows')"
        shell: bash
        run: |
          cmakebuild/bin/cafPdmCore_UnitTests
          cmakebuild/bin/cafPdmIoCore_UnitTests
          cmakebuild/bin/cafProjectDataModel_UnitTests
          cmakebuild/bin/cafGrpcInterface_UnitTests
          
