name: Build with Unit Tests

on: [push, pull_request]
jobs:
  caffa-x64:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        include:
          - os: ubuntu-20.04
            triplet: x64-linux

    steps:
      - name: Install gRPC
        run: sudo apt-get install libgrpc++-dev libprotoc-dev protobuf-compiler-grpc libboost-dev
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build Caffa with Unit Tests
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          cmakeAppendedArgs: '-DCAFFA_GRPC_INTERFACE=ON -DCAFFA_BUILD_UNIT_TESTS=ON'
          buildDirectory: ${{ github.workspace }}/cmakebuild
          buildWithCMakeArgs: '--config Release'
      - name: Run Unit Tests Linux
        shell: bash
        run: |
          cmakebuild/bin/caffaCore_UnitTests
          cmakebuild/bin/caffaIoCore_UnitTests
          cmakebuild/bin/caffaProjectDataModel_UnitTests
          cmakebuild/bin/caffaGrpcInterface_UnitTests

