name: Build with Unit Tests Windows

on: [push, pull_request]
jobs:
  caffa-x64:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build Caffa with Unit Tests
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          cmakeAppendedArgs: '-DCAFFA_BUILD_EXAMPLES=ON -DCAFFA_BUILD_UNIT_TESTS=ON'
          buildDirectory: ${{ github.workspace }}/cmakebuild
          buildWithCMakeArgs: '--config Release'
      - name: Run Unit Tests Windows
        shell: bash
        run: |
          cmakebuild/bin/Release/caffaCore_UnitTests.exe
          cmakebuild/bin/Release/caffaIoCore_UnitTests.exe
          cmakebuild/bin/Release/caffaProjectDataModel_UnitTests.exe

