name: Build with Unit Tests Windows/MacOS

on: [push, pull_request]
jobs:
  caffa-x64:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: macos-latest
            triplet: x64-osx
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install boost
        uses: MarkusJx/install-boost@v2.0.0
        id: install-boost
        with:
            boost_version: 1.73.0
      - name: Build Caffa with Unit Tests
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          cmakeAppendedArgs: '-DCAFFA_GRPC_INTERFACE=OFF -DCAFFA_BUILD_UNIT_TESTS=ON -DBOOST_ROOT=${{ steps.install-boost.outputs.BOOST_ROOT }}'
          buildDirectory: ${{ github.workspace }}/cmakebuild
          buildWithCMakeArgs: '--config Release'
      - name: Run Unit Tests MacOS
        if: "!contains( matrix.os, 'windows')"
        shell: bash
        run: |
          cmakebuild/bin/caffaCore_UnitTests
          cmakebuild/bin/caffaIoCore_UnitTests
          cmakebuild/bin/caffaProjectDataModel_UnitTests
      - name: Run Unit Tests Windows
        if: contains( matrix.os, 'windows')  
        shell: bash
        run: |
          cmakebuild/bin/Release/caffaCore_UnitTests.exe
          cmakebuild/bin/Release/caffaIoCore_UnitTests.exe
          cmakebuild/bin/Release/caffaProjectDataModel_UnitTests.exe

