name: Build with Unit Tests

on: [push, pull_request]
jobs:
  caffa-x64:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-20.04
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build Caffa with Unit Tests
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          cmakeAppendedArgs: '-DCAFFA_GRPC_INTERFACE=ON -DCAFFA_BUILD_UNIT_TESTS=ON'
          buildDirectory: ${{ github.workspace }}/cmakebuild
          buildWithCMakeArgs: '--config Release'
      - name: Run Unit Tests Linux/MacOS
        if: "!contains( matrix.os, 'windows')"
        shell: bash
        run: |
          cmakebuild/bin/cafPdmCore_UnitTests
          cmakebuild/bin/cafPdmIoCore_UnitTests
          cmakebuild/bin/cafProjectDataModel_UnitTests
          cmakebuild/bin/cafGrpcInterface_UnitTests
      - name: Run Unit Tests Windows
        if: contains( matrix.os, 'windows')  
        shell: bash
        run: |
          cmakebuild/bin/Release/cafPdmCore_UnitTests.exe
          cmakebuild/bin/Release/cafPdmIoCore_UnitTests.exe
          cmakebuild/bin/Release/cafProjectDataModel_UnitTests.exe
          cmakebuild/bin/Release/cafGrpcInterface_UnitTests.exe
          
