name: Build with Unit Tests Windows/MacOS

on: [push, pull_request]
jobs:
  caffa-x64:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: macos-latest
            triplet: x64-osx
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build Caffa with Unit Tests
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          cmakeAppendedArgs: '-DCAFFA_GRPC_INTERFACE=OFF -DCAFFA_BUILD_UNIT_TESTS=ON'
          buildDirectory: ${{ github.workspace }}/cmakebuild
          buildWithCMakeArgs: '--config Release'
      - name: Run Unit Tests MacOS
        shell: bash
        run: |
          cmakebuild/bin/cafCore_UnitTests
          cmakebuild/bin/cafIoCore_UnitTests
          cmakebuild/bin/cafProjectDataModel_UnitTests
      - name: Run Unit Tests Windows
        if: contains( matrix.os, 'windows')  
        shell: bash
        run: |
          cmakebuild/bin/Release/cafCore_UnitTests.exe
          cmakebuild/bin/Release/cafIoCore_UnitTests.exe
          cmakebuild/bin/Release/cafProjectDataModel_UnitTests.exe

