name: Build with Unit Tests Windows

on: [push, pull_request]
jobs:
  caffa-x64:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install boost
        uses: MarkusJx/install-boost@v2.0.0
        id: install-boost
        with:
            boost_version: 1.77.0
            platform_version: 2019
      - name: Setup gRPC
        uses: eWaterCycle/setup-grpc@v5
        with:
          grpc-version: 1.35.0
      - name: Build Caffa with Unit Tests
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          cmakeAppendedArgs: '-DCAFFA_GRPC_INTERFACE=ON -DCAFFA_BUILD_EXAMPLES=ON -DCAFFA_BUILD_UNIT_TESTS=ON -DBOOST_ROOT=${{ steps.install-boost.outputs.BOOST_ROOT }}'
          buildDirectory: ${{ github.workspace }}/cmakebuild
          buildWithCMakeArgs: '--config Release'
      - name: Run Unit Tests Windows
        shell: bash
        run: |
          cmakebuild/bin/Release/caffaCore_UnitTests.exe
          cmakebuild/bin/Release/caffaIoCore_UnitTests.exe
          cmakebuild/bin/Release/caffaProjectDataModel_UnitTests.exe
          cmakebuild/bin/Release/caffaGrpcInterface_UnitTests.exe
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Python modules
        run: |
          python -m pip install --upgrade pip
          pip install grpcio-tools setuptools pytest
      - name: Run pytest
        run: |
          cmd /c "start /B \"\" cmakebuild/bin/Release/caffaGrpcInterface_ExampleServer.exe"
          timeout 4 > NUL
          cd Bindings/Python/caffa
          python -m pytest --log-cli-level=DEBUG