name: Build with Unit Tests

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
jobs:
  caffa:
    runs-on: ubuntu-24.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtest-dev \
            libboost-dev libboost-regex-dev libboost-json-dev
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.28.0"
      - name: Configure Caffa
        uses: lukka/run-cmake@v10.7
        with:
          configurePreset: 'ninja-multi'
      - name: Build Caffa
        uses: lukka/run-cmake@v10.7
        with:
          buildPreset: 'ninja-release'
      - name: Run Caffa Unit Tests
        uses: lukka/run-cmake@v10.7
        with:
          testPreset: 'test-release'
