name: Create ARM Docker Container

on:  
  push:    
    branches: [ master ]
  pull_request:
jobs:   
  build:    
    runs-on: ubuntu-20.04    
    env:      
      DOCKER_REGISTRY: hub.docker.com
      DOCKER_IMAGE: lindkvis/caffa_arm32v7:0.2
    steps:    
    - name: Checkout     
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Get git SHAs
      id: vars
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Set up Docker Buildx      
      uses: docker/setup-buildx-action@v1
      with:        
        version: latest
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          push: true
          tags: lindkvis/caffa_arm32v7:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
